using System.IO;
using Org.Apache.Hadoop.Util;


namespace Org.Apache.Hadoop.IO.Nativeio
{
	/// <summary>An exception generated by a call to the native IO code.</summary>
	/// <remarks>
	/// An exception generated by a call to the native IO code.
	/// These exceptions simply wrap <i>errno</i> result codes on Linux,
	/// or the System Error Code on Windows.
	/// </remarks>
	[System.Serializable]
	public class NativeIOException : IOException
	{
		private const long serialVersionUID = 1L;

		private Errno errno;

		private int errorCode;

		public NativeIOException(string msg, Errno errno)
			: base(msg)
		{
			// Java has no unsigned primitive error code. Use a signed 32-bit
			// integer to hold the unsigned 32-bit integer.
			this.errno = errno;
			// Windows error code is always set to ERROR_SUCCESS on Linux,
			// i.e. no failure on Windows
			this.errorCode = 0;
		}

		public NativeIOException(string msg, int errorCode)
			: base(msg)
		{
			this.errorCode = errorCode;
			this.errno = Errno.Unknown;
		}

		public virtual long GetErrorCode()
		{
			return errorCode;
		}

		public virtual Errno GetErrno()
		{
			return errno;
		}

		public override string ToString()
		{
			if (Shell.Windows)
			{
				return errorCode + ": " + base.Message;
			}
			else
			{
				return errno.ToString() + ": " + base.Message;
			}
		}
	}
}
