// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_rpc_service.proto
using Sharpen;

namespace org.apache.hadoop.ipc.protobuf
{
	public sealed class TestRpcServiceProtos
	{
		private TestRpcServiceProtos()
		{
		}

		public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry
			)
		{
		}

		/// <summary>
		/// Protobuf service
		/// <c>hadoop.common.TestProtobufRpcProto</c>
		/// <pre>
		/// A protobuf service for use in tests
		/// </pre>
		/// </summary>
		public abstract class TestProtobufRpcProto : com.google.protobuf.Service
		{
			protected internal TestProtobufRpcProto()
			{
			}

			public interface Interface
			{
				/// <summary><code>rpc ping(.hadoop.common.EmptyRequestProto) returns (.hadoop.common.EmptyResponseProto);</code>
				/// 	</summary>
				void ping(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done);

				/// <summary><code>rpc echo(.hadoop.common.EchoRequestProto) returns (.hadoop.common.EchoResponseProto);</code>
				/// 	</summary>
				void echo(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
					> done);

				/// <summary><code>rpc error(.hadoop.common.EmptyRequestProto) returns (.hadoop.common.EmptyResponseProto);</code>
				/// 	</summary>
				void error(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done);

				/// <summary><code>rpc error2(.hadoop.common.EmptyRequestProto) returns (.hadoop.common.EmptyResponseProto);</code>
				/// 	</summary>
				void error2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done);
			}

			public static com.google.protobuf.Service newReflectiveService(org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.Interface
				 impl)
			{
				return new _TestProtobufRpcProto_60(impl);
			}

			private sealed class _TestProtobufRpcProto_60 : org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto
			{
				public _TestProtobufRpcProto_60(org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.Interface
					 impl)
				{
					this.impl = impl;
				}

				public override void ping(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done)
				{
					impl.ping(controller, request, done);
				}

				public override void echo(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
					> done)
				{
					impl.echo(controller, request, done);
				}

				public override void error(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done)
				{
					impl.error(controller, request, done);
				}

				public override void error2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done)
				{
					impl.error2(controller, request, done);
				}

				private readonly org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.Interface
					 impl;
			}

			public static com.google.protobuf.BlockingService newReflectiveBlockingService(org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.BlockingInterface
				 impl)
			{
				return new _BlockingService_98(impl);
			}

			private sealed class _BlockingService_98 : com.google.protobuf.BlockingService
			{
				public _BlockingService_98(org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.BlockingInterface
					 impl)
				{
					this.impl = impl;
				}

				public com.google.protobuf.Descriptors.ServiceDescriptor getDescriptorForType()
				{
					return org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.getDescriptor
						();
				}

				/// <exception cref="com.google.protobuf.ServiceException"/>
				public com.google.protobuf.Message callBlockingMethod(com.google.protobuf.Descriptors.MethodDescriptor
					 method, com.google.protobuf.RpcController controller, com.google.protobuf.Message
					 request)
				{
					if (method.getService() != org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto
						.getDescriptor())
					{
						throw new System.ArgumentException("Service.callBlockingMethod() given method descriptor for "
							 + "wrong service type.");
					}
					switch (method.getIndex())
					{
						case 0:
						{
							return impl.ping(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
								)request);
						}

						case 1:
						{
							return impl.echo(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
								)request);
						}

						case 2:
						{
							return impl.error(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
								)request);
						}

						case 3:
						{
							return impl.error2(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
								)request);
						}

						default:
						{
							throw new java.lang.AssertionError("Can't get here.");
						}
					}
				}

				public com.google.protobuf.Message getRequestPrototype(com.google.protobuf.Descriptors.MethodDescriptor
					 method)
				{
					if (method.getService() != org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto
						.getDescriptor())
					{
						throw new System.ArgumentException("Service.getRequestPrototype() given method " 
							+ "descriptor for wrong service type.");
					}
					switch (method.getIndex())
					{
						case 0:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto.getDefaultInstance
								();
						}

						case 1:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto.getDefaultInstance
								();
						}

						case 2:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto.getDefaultInstance
								();
						}

						case 3:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto.getDefaultInstance
								();
						}

						default:
						{
							throw new java.lang.AssertionError("Can't get here.");
						}
					}
				}

				public com.google.protobuf.Message getResponsePrototype(com.google.protobuf.Descriptors.MethodDescriptor
					 method)
				{
					if (method.getService() != org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto
						.getDescriptor())
					{
						throw new System.ArgumentException("Service.getResponsePrototype() given method "
							 + "descriptor for wrong service type.");
					}
					switch (method.getIndex())
					{
						case 0:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
								();
						}

						case 1:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto.getDefaultInstance
								();
						}

						case 2:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
								();
						}

						case 3:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
								();
						}

						default:
						{
							throw new java.lang.AssertionError("Can't get here.");
						}
					}
				}

				private readonly org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.BlockingInterface
					 impl;
			}

			/// <summary><code>rpc ping(.hadoop.common.EmptyRequestProto) returns (.hadoop.common.EmptyResponseProto);</code>
			/// 	</summary>
			public abstract void ping(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
				 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
				> done);

			/// <summary><code>rpc echo(.hadoop.common.EchoRequestProto) returns (.hadoop.common.EchoResponseProto);</code>
			/// 	</summary>
			public abstract void echo(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
				 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
				> done);

			/// <summary><code>rpc error(.hadoop.common.EmptyRequestProto) returns (.hadoop.common.EmptyResponseProto);</code>
			/// 	</summary>
			public abstract void error(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
				 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
				> done);

			/// <summary><code>rpc error2(.hadoop.common.EmptyRequestProto) returns (.hadoop.common.EmptyResponseProto);</code>
			/// 	</summary>
			public abstract void error2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
				 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
				> done);

			public static com.google.protobuf.Descriptors.ServiceDescriptor getDescriptor()
			{
				return org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.getDescriptor().getServices
					()[0];
			}

			public com.google.protobuf.Descriptors.ServiceDescriptor getDescriptorForType()
			{
				return getDescriptor();
			}

			public void callMethod(com.google.protobuf.Descriptors.MethodDescriptor method, com.google.protobuf.RpcController
				 controller, com.google.protobuf.Message request, com.google.protobuf.RpcCallback
				<com.google.protobuf.Message> done)
			{
				if (method.getService() != getDescriptor())
				{
					throw new System.ArgumentException("Service.callMethod() given method descriptor for wrong "
						 + "service type.");
				}
				switch (method.getIndex())
				{
					case 0:
					{
						this.ping(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
							)request, com.google.protobuf.RpcUtil.specializeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
							>(done));
						return;
					}

					case 1:
					{
						this.echo(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
							)request, com.google.protobuf.RpcUtil.specializeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
							>(done));
						return;
					}

					case 2:
					{
						this.error(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
							)request, com.google.protobuf.RpcUtil.specializeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
							>(done));
						return;
					}

					case 3:
					{
						this.error2(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
							)request, com.google.protobuf.RpcUtil.specializeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
							>(done));
						return;
					}

					default:
					{
						throw new java.lang.AssertionError("Can't get here.");
					}
				}
			}

			public com.google.protobuf.Message getRequestPrototype(com.google.protobuf.Descriptors.MethodDescriptor
				 method)
			{
				if (method.getService() != getDescriptor())
				{
					throw new System.ArgumentException("Service.getRequestPrototype() given method " 
						+ "descriptor for wrong service type.");
				}
				switch (method.getIndex())
				{
					case 0:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto.getDefaultInstance
							();
					}

					case 1:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto.getDefaultInstance
							();
					}

					case 2:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto.getDefaultInstance
							();
					}

					case 3:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto.getDefaultInstance
							();
					}

					default:
					{
						throw new java.lang.AssertionError("Can't get here.");
					}
				}
			}

			public com.google.protobuf.Message getResponsePrototype(com.google.protobuf.Descriptors.MethodDescriptor
				 method)
			{
				if (method.getService() != getDescriptor())
				{
					throw new System.ArgumentException("Service.getResponsePrototype() given method "
						 + "descriptor for wrong service type.");
				}
				switch (method.getIndex())
				{
					case 0:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
							();
					}

					case 1:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto.getDefaultInstance
							();
					}

					case 2:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
							();
					}

					case 3:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
							();
					}

					default:
					{
						throw new java.lang.AssertionError("Can't get here.");
					}
				}
			}

			public static org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.Stub
				 newStub(com.google.protobuf.RpcChannel channel)
			{
				return new org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.Stub
					(channel);
			}

			public sealed class Stub : org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto
				, org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.Interface
			{
				private Stub(com.google.protobuf.RpcChannel channel)
				{
					this.channel = channel;
				}

				private readonly com.google.protobuf.RpcChannel channel;

				public com.google.protobuf.RpcChannel getChannel()
				{
					return channel;
				}

				public override void ping(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done)
				{
					channel.callMethod(getDescriptor().getMethods()[0], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						.getDefaultInstance(), com.google.protobuf.RpcUtil.generalizeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						>(done, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
						()));
				}

				public override void echo(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
					> done)
				{
					channel.callMethod(getDescriptor().getMethods()[1], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
						.getDefaultInstance(), com.google.protobuf.RpcUtil.generalizeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
						>(done, org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto.getDefaultInstance
						()));
				}

				public override void error(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done)
				{
					channel.callMethod(getDescriptor().getMethods()[2], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						.getDefaultInstance(), com.google.protobuf.RpcUtil.generalizeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						>(done, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
						()));
				}

				public override void error2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done)
				{
					channel.callMethod(getDescriptor().getMethods()[3], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						.getDefaultInstance(), com.google.protobuf.RpcUtil.generalizeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						>(done, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
						()));
				}
			}

			public static org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.BlockingInterface
				 newBlockingStub(com.google.protobuf.BlockingRpcChannel channel)
			{
				return new org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.BlockingStub
					(channel);
			}

			public interface BlockingInterface
			{
				/// <exception cref="com.google.protobuf.ServiceException"/>
				org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto ping(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto request
					);

				/// <exception cref="com.google.protobuf.ServiceException"/>
				org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto echo(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto request);

				/// <exception cref="com.google.protobuf.ServiceException"/>
				org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto error(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto request
					);

				/// <exception cref="com.google.protobuf.ServiceException"/>
				org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto error2(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto request
					);
			}

			private sealed class BlockingStub : org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpcProto.BlockingInterface
			{
				private BlockingStub(com.google.protobuf.BlockingRpcChannel channel)
				{
					this.channel = channel;
				}

				private readonly com.google.protobuf.BlockingRpcChannel channel;

				/// <exception cref="com.google.protobuf.ServiceException"/>
				public org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto ping(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto request
					)
				{
					return (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto)channel.callBlockingMethod
						(getDescriptor().getMethods()[0], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						.getDefaultInstance());
				}

				/// <exception cref="com.google.protobuf.ServiceException"/>
				public org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto echo(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto request)
				{
					return (org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto)channel.callBlockingMethod
						(getDescriptor().getMethods()[1], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
						.getDefaultInstance());
				}

				/// <exception cref="com.google.protobuf.ServiceException"/>
				public org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto error(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto request
					)
				{
					return (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto)channel.callBlockingMethod
						(getDescriptor().getMethods()[2], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						.getDefaultInstance());
				}

				/// <exception cref="com.google.protobuf.ServiceException"/>
				public org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto error2(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto request
					)
				{
					return (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto)channel.callBlockingMethod
						(getDescriptor().getMethods()[3], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						.getDefaultInstance());
				}
			}
			// @@protoc_insertion_point(class_scope:hadoop.common.TestProtobufRpcProto)
		}

		/// <summary>
		/// Protobuf service
		/// <c>hadoop.common.TestProtobufRpc2Proto</c>
		/// </summary>
		public abstract class TestProtobufRpc2Proto : com.google.protobuf.Service
		{
			protected internal TestProtobufRpc2Proto()
			{
			}

			public interface Interface
			{
				/// <summary><code>rpc ping2(.hadoop.common.EmptyRequestProto) returns (.hadoop.common.EmptyResponseProto);</code>
				/// 	</summary>
				void ping2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done);

				/// <summary><code>rpc echo2(.hadoop.common.EchoRequestProto) returns (.hadoop.common.EchoResponseProto);</code>
				/// 	</summary>
				void echo2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
					> done);
			}

			public static com.google.protobuf.Service newReflectiveService(org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.Interface
				 impl)
			{
				return new _TestProtobufRpc2Proto_489(impl);
			}

			private sealed class _TestProtobufRpc2Proto_489 : org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto
			{
				public _TestProtobufRpc2Proto_489(org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.Interface
					 impl)
				{
					this.impl = impl;
				}

				public override void ping2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done)
				{
					impl.ping2(controller, request, done);
				}

				public override void echo2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
					> done)
				{
					impl.echo2(controller, request, done);
				}

				private readonly org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.Interface
					 impl;
			}

			public static com.google.protobuf.BlockingService newReflectiveBlockingService(org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.BlockingInterface
				 impl)
			{
				return new _BlockingService_511(impl);
			}

			private sealed class _BlockingService_511 : com.google.protobuf.BlockingService
			{
				public _BlockingService_511(org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.BlockingInterface
					 impl)
				{
					this.impl = impl;
				}

				public com.google.protobuf.Descriptors.ServiceDescriptor getDescriptorForType()
				{
					return org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.
						getDescriptor();
				}

				/// <exception cref="com.google.protobuf.ServiceException"/>
				public com.google.protobuf.Message callBlockingMethod(com.google.protobuf.Descriptors.MethodDescriptor
					 method, com.google.protobuf.RpcController controller, com.google.protobuf.Message
					 request)
				{
					if (method.getService() != org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto
						.getDescriptor())
					{
						throw new System.ArgumentException("Service.callBlockingMethod() given method descriptor for "
							 + "wrong service type.");
					}
					switch (method.getIndex())
					{
						case 0:
						{
							return impl.ping2(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
								)request);
						}

						case 1:
						{
							return impl.echo2(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
								)request);
						}

						default:
						{
							throw new java.lang.AssertionError("Can't get here.");
						}
					}
				}

				public com.google.protobuf.Message getRequestPrototype(com.google.protobuf.Descriptors.MethodDescriptor
					 method)
				{
					if (method.getService() != org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto
						.getDescriptor())
					{
						throw new System.ArgumentException("Service.getRequestPrototype() given method " 
							+ "descriptor for wrong service type.");
					}
					switch (method.getIndex())
					{
						case 0:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto.getDefaultInstance
								();
						}

						case 1:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto.getDefaultInstance
								();
						}

						default:
						{
							throw new java.lang.AssertionError("Can't get here.");
						}
					}
				}

				public com.google.protobuf.Message getResponsePrototype(com.google.protobuf.Descriptors.MethodDescriptor
					 method)
				{
					if (method.getService() != org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto
						.getDescriptor())
					{
						throw new System.ArgumentException("Service.getResponsePrototype() given method "
							 + "descriptor for wrong service type.");
					}
					switch (method.getIndex())
					{
						case 0:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
								();
						}

						case 1:
						{
							return org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto.getDefaultInstance
								();
						}

						default:
						{
							throw new java.lang.AssertionError("Can't get here.");
						}
					}
				}

				private readonly org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.BlockingInterface
					 impl;
			}

			/// <summary><code>rpc ping2(.hadoop.common.EmptyRequestProto) returns (.hadoop.common.EmptyResponseProto);</code>
			/// 	</summary>
			public abstract void ping2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
				 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
				> done);

			/// <summary><code>rpc echo2(.hadoop.common.EchoRequestProto) returns (.hadoop.common.EchoResponseProto);</code>
			/// 	</summary>
			public abstract void echo2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
				 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
				> done);

			public static com.google.protobuf.Descriptors.ServiceDescriptor getDescriptor()
			{
				return org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.getDescriptor().getServices
					()[1];
			}

			public com.google.protobuf.Descriptors.ServiceDescriptor getDescriptorForType()
			{
				return getDescriptor();
			}

			public void callMethod(com.google.protobuf.Descriptors.MethodDescriptor method, com.google.protobuf.RpcController
				 controller, com.google.protobuf.Message request, com.google.protobuf.RpcCallback
				<com.google.protobuf.Message> done)
			{
				if (method.getService() != getDescriptor())
				{
					throw new System.ArgumentException("Service.callMethod() given method descriptor for wrong "
						 + "service type.");
				}
				switch (method.getIndex())
				{
					case 0:
					{
						this.ping2(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
							)request, com.google.protobuf.RpcUtil.specializeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
							>(done));
						return;
					}

					case 1:
					{
						this.echo2(controller, (org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
							)request, com.google.protobuf.RpcUtil.specializeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
							>(done));
						return;
					}

					default:
					{
						throw new java.lang.AssertionError("Can't get here.");
					}
				}
			}

			public com.google.protobuf.Message getRequestPrototype(com.google.protobuf.Descriptors.MethodDescriptor
				 method)
			{
				if (method.getService() != getDescriptor())
				{
					throw new System.ArgumentException("Service.getRequestPrototype() given method " 
						+ "descriptor for wrong service type.");
				}
				switch (method.getIndex())
				{
					case 0:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto.getDefaultInstance
							();
					}

					case 1:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto.getDefaultInstance
							();
					}

					default:
					{
						throw new java.lang.AssertionError("Can't get here.");
					}
				}
			}

			public com.google.protobuf.Message getResponsePrototype(com.google.protobuf.Descriptors.MethodDescriptor
				 method)
			{
				if (method.getService() != getDescriptor())
				{
					throw new System.ArgumentException("Service.getResponsePrototype() given method "
						 + "descriptor for wrong service type.");
				}
				switch (method.getIndex())
				{
					case 0:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
							();
					}

					case 1:
					{
						return org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto.getDefaultInstance
							();
					}

					default:
					{
						throw new java.lang.AssertionError("Can't get here.");
					}
				}
			}

			public static org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.Stub
				 newStub(com.google.protobuf.RpcChannel channel)
			{
				return new org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.Stub
					(channel);
			}

			public sealed class Stub : org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto
				, org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.Interface
			{
				private Stub(com.google.protobuf.RpcChannel channel)
				{
					this.channel = channel;
				}

				private readonly com.google.protobuf.RpcChannel channel;

				public com.google.protobuf.RpcChannel getChannel()
				{
					return channel;
				}

				public override void ping2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
					> done)
				{
					channel.callMethod(getDescriptor().getMethods()[0], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						.getDefaultInstance(), com.google.protobuf.RpcUtil.generalizeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						>(done, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto.getDefaultInstance
						()));
				}

				public override void echo2(com.google.protobuf.RpcController controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto
					 request, com.google.protobuf.RpcCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
					> done)
				{
					channel.callMethod(getDescriptor().getMethods()[1], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
						.getDefaultInstance(), com.google.protobuf.RpcUtil.generalizeCallback<org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
						>(done, org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto.getDefaultInstance
						()));
				}
			}

			public static org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.BlockingInterface
				 newBlockingStub(com.google.protobuf.BlockingRpcChannel channel)
			{
				return new org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.BlockingStub
					(channel);
			}

			public interface BlockingInterface
			{
				/// <exception cref="com.google.protobuf.ServiceException"/>
				org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto ping2(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto request
					);

				/// <exception cref="com.google.protobuf.ServiceException"/>
				org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto echo2(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto request);
			}

			private sealed class BlockingStub : org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.TestProtobufRpc2Proto.BlockingInterface
			{
				private BlockingStub(com.google.protobuf.BlockingRpcChannel channel)
				{
					this.channel = channel;
				}

				private readonly com.google.protobuf.BlockingRpcChannel channel;

				/// <exception cref="com.google.protobuf.ServiceException"/>
				public org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto ping2(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyRequestProto request
					)
				{
					return (org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto)channel.callBlockingMethod
						(getDescriptor().getMethods()[0], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EmptyResponseProto
						.getDefaultInstance());
				}

				/// <exception cref="com.google.protobuf.ServiceException"/>
				public org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto echo2(com.google.protobuf.RpcController
					 controller, org.apache.hadoop.ipc.protobuf.TestProtos.EchoRequestProto request)
				{
					return (org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto)channel.callBlockingMethod
						(getDescriptor().getMethods()[1], controller, request, org.apache.hadoop.ipc.protobuf.TestProtos.EchoResponseProto
						.getDefaultInstance());
				}
			}
			// @@protoc_insertion_point(class_scope:hadoop.common.TestProtobufRpc2Proto)
		}

		public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor()
		{
			return descriptor;
		}

		private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

		static TestRpcServiceProtos()
		{
			string[] descriptorData = new string[] { "\n\x1atest_rpc_service.proto\x16\rhadoop.common\x20"
				 + "\ntest.proto2\x139\x2\n\x18TestProtobufRpcProto\x16K\n\x4" + "ping\x16 .hadoop.common.EmptyRequestProto\x20!"
				 + ".hadoop.common.EmptyResponseProto\x16I\n\x4ech" + "o\x16\x25.hadoop.common.EchoRequestProto\x20 .had"
				 + "oop.common.EchoResponseProto\x16L\n\x5error\x16 ." + "hadoop.common.EmptyRequestProto\x20!.hadoop"
				 + ".common.EmptyResponseProto\x16M\n\x6error2\x16 .h" + "adoop.common.EmptyRequestProto\x20!.hadoop."
				 + "common.EmptyResponseProto2\x105\x1\n\x19TestProtob", "ufRpc2Proto\x16L\n\x5ping2\x16 .hadoop.common.Emp"
				 + "tyRequestProto\x20!.hadoop.common.EmptyResp" + "onseProto\x16J\n\x5echo2\x16\x25.hadoop.common.EchoR"
				 + "equestProto\x20 .hadoop.common.EchoResponse" + "ProtoB<\n\x24org.apache.hadoop.ipc.protobufB"
				 + "\x18TestRpcServiceProtos\xd2\x1\x1\xf0\x1\x1" };
			com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner
				 = new _InternalDescriptorAssigner_791();
			com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData
				, new com.google.protobuf.Descriptors.FileDescriptor[] { org.apache.hadoop.ipc.protobuf.TestProtos
				.getDescriptor() }, assigner);
		}

		private sealed class _InternalDescriptorAssigner_791 : com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner
		{
			public _InternalDescriptorAssigner_791()
			{
			}

			public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor
				 root)
			{
				org.apache.hadoop.ipc.protobuf.TestRpcServiceProtos.descriptor = root;
				return null;
			}
		}
		// @@protoc_insertion_point(outer_class_scope)
	}
}
