using System.Collections.Generic;
using Org.Apache.Hadoop.Yarn.Api.Records;
using Org.Apache.Hadoop.Yarn.Server.Nodemanager.Containermanager.Localizer;
using Sharpen;

namespace Org.Apache.Hadoop.Yarn.Server.Nodemanager.Containermanager.Localizer.Event
{
	/// <summary>
	/// Event that requests that the
	/// <see cref="Org.Apache.Hadoop.Yarn.Server.Nodemanager.Containermanager.Localizer.ResourceLocalizationService
	/// 	"/>
	/// localize
	/// a set of resources for the given container. This is generated by
	/// <see cref="Org.Apache.Hadoop.Yarn.Server.Nodemanager.Containermanager.Container.ContainerImpl
	/// 	"/>
	/// during container initialization.
	/// </summary>
	public class ContainerLocalizationRequestEvent : ContainerLocalizationEvent
	{
		private readonly IDictionary<LocalResourceVisibility, ICollection<LocalResourceRequest
			>> rsrc;

		/// <summary>Event requesting the localization of the rsrc.</summary>
		/// <param name="c"/>
		/// <param name="rsrc"/>
		public ContainerLocalizationRequestEvent(Org.Apache.Hadoop.Yarn.Server.Nodemanager.Containermanager.Container.Container
			 c, IDictionary<LocalResourceVisibility, ICollection<LocalResourceRequest>> rsrc
			)
			: base(LocalizationEventType.InitContainerResources, c)
		{
			this.rsrc = rsrc;
		}

		public virtual IDictionary<LocalResourceVisibility, ICollection<LocalResourceRequest
			>> GetRequestedResources()
		{
			return rsrc;
		}
	}
}
