using Sharpen;

namespace Org.Apache.Hadoop.Yarn.Server.Timeline
{
	/// <summary>The unique identifier for an entity</summary>
	public class EntityIdentifier : Comparable<Org.Apache.Hadoop.Yarn.Server.Timeline.EntityIdentifier
		>
	{
		private string id;

		private string type;

		public EntityIdentifier(string id, string type)
		{
			this.id = id;
			this.type = type;
		}

		/// <summary>Get the entity Id.</summary>
		/// <returns>The entity Id.</returns>
		public virtual string GetId()
		{
			return id;
		}

		/// <summary>Get the entity type.</summary>
		/// <returns>The entity type.</returns>
		public virtual string GetType()
		{
			return type;
		}

		public virtual int CompareTo(Org.Apache.Hadoop.Yarn.Server.Timeline.EntityIdentifier
			 other)
		{
			int c = string.CompareOrdinal(type, other.type);
			if (c != 0)
			{
				return c;
			}
			return string.CompareOrdinal(id, other.id);
		}

		public override int GetHashCode()
		{
			// generated by eclipse
			int prime = 31;
			int result = 1;
			result = prime * result + ((id == null) ? 0 : id.GetHashCode());
			result = prime * result + ((type == null) ? 0 : type.GetHashCode());
			return result;
		}

		public override bool Equals(object obj)
		{
			// generated by eclipse
			if (this == obj)
			{
				return true;
			}
			if (obj == null)
			{
				return false;
			}
			if (GetType() != obj.GetType())
			{
				return false;
			}
			Org.Apache.Hadoop.Yarn.Server.Timeline.EntityIdentifier other = (Org.Apache.Hadoop.Yarn.Server.Timeline.EntityIdentifier
				)obj;
			if (id == null)
			{
				if (other.id != null)
				{
					return false;
				}
			}
			else
			{
				if (!id.Equals(other.id))
				{
					return false;
				}
			}
			if (type == null)
			{
				if (other.type != null)
				{
					return false;
				}
			}
			else
			{
				if (!type.Equals(other.type))
				{
					return false;
				}
			}
			return true;
		}

		public override string ToString()
		{
			return "{ id: " + id + ", type: " + type + " }";
		}
	}
}
