using Sharpen;

namespace org.apache.hadoop.fs
{
	/// <summary>Generated by rm commands</summary>
	[System.Serializable]
	public class PathIsNotEmptyDirectoryException : org.apache.hadoop.fs.PathExistsException
	{
		/// <param name="path">for the exception</param>
		public PathIsNotEmptyDirectoryException(string path)
			: base(path, "Directory is not empty")
		{
		}
	}
}
