using Sharpen;

namespace org.apache.hadoop.record.compiler
{
	/// <summary>C Code generator front-end for Hadoop record I/O.</summary>
	internal class CGenerator : org.apache.hadoop.record.compiler.CodeGenerator
	{
		internal CGenerator()
		{
		}

		/// <summary>Generate C code.</summary>
		/// <remarks>
		/// Generate C code. This method only creates the requested file(s)
		/// and spits-out file-level elements (such as include statements etc.)
		/// record-level code is generated by JRecord.
		/// </remarks>
		/// <exception cref="System.IO.IOException"/>
		internal override void genCode(string name, System.Collections.Generic.List<org.apache.hadoop.record.compiler.JFile
			> ilist, System.Collections.Generic.List<org.apache.hadoop.record.compiler.JRecord
			> rlist, string destDir, System.Collections.Generic.List<string> options)
		{
			name = new java.io.File(destDir, (new java.io.File(name)).getName()).getAbsolutePath
				();
			java.io.FileWriter cc = new java.io.FileWriter(name + ".c");
			try
			{
				java.io.FileWriter hh = new java.io.FileWriter(name + ".h");
				try
				{
					hh.write("#ifndef __" + org.apache.hadoop.util.StringUtils.toUpperCase(name).Replace
						('.', '_') + "__\n");
					hh.write("#define __" + org.apache.hadoop.util.StringUtils.toUpperCase(name).Replace
						('.', '_') + "__\n");
					hh.write("#include \"recordio.h\"\n");
					for (System.Collections.Generic.IEnumerator<org.apache.hadoop.record.compiler.JFile
						> iter = ilist.GetEnumerator(); iter.MoveNext(); )
					{
						hh.write("#include \"" + iter.Current.getName() + ".h\"\n");
					}
					cc.write("#include \"" + name + ".h\"\n");
					/*
					for (Iterator<JRecord> iter = rlist.iterator(); iter.hasNext();) {
					iter.next().genCppCode(hh, cc);
					}
					*/
					hh.write("#endif //" + org.apache.hadoop.util.StringUtils.toUpperCase(name).Replace
						('.', '_') + "__\n");
				}
				finally
				{
					hh.close();
				}
			}
			finally
			{
				cc.close();
			}
		}
	}
}
