using Sharpen;

namespace org.apache.hadoop.record.compiler
{
	/// <summary>C++ Code generator front-end for Hadoop record I/O.</summary>
	internal class CppGenerator : org.apache.hadoop.record.compiler.CodeGenerator
	{
		internal CppGenerator()
		{
		}

		/// <summary>Generate C++ code.</summary>
		/// <remarks>
		/// Generate C++ code. This method only creates the requested file(s)
		/// and spits-out file-level elements (such as include statements etc.)
		/// record-level code is generated by JRecord.
		/// </remarks>
		/// <exception cref="System.IO.IOException"/>
		internal override void genCode(string name, System.Collections.Generic.List<org.apache.hadoop.record.compiler.JFile
			> ilist, System.Collections.Generic.List<org.apache.hadoop.record.compiler.JRecord
			> rlist, string destDir, System.Collections.Generic.List<string> options)
		{
			name = new java.io.File(destDir, (new java.io.File(name)).getName()).getAbsolutePath
				();
			java.io.FileWriter cc = new java.io.FileWriter(name + ".cc");
			try
			{
				java.io.FileWriter hh = new java.io.FileWriter(name + ".hh");
				try
				{
					string fileName = (new java.io.File(name)).getName();
					hh.write("#ifndef __" + org.apache.hadoop.util.StringUtils.toUpperCase(fileName).
						Replace('.', '_') + "__\n");
					hh.write("#define __" + org.apache.hadoop.util.StringUtils.toUpperCase(fileName).
						Replace('.', '_') + "__\n");
					hh.write("#include \"recordio.hh\"\n");
					hh.write("#include \"recordTypeInfo.hh\"\n");
					for (System.Collections.Generic.IEnumerator<org.apache.hadoop.record.compiler.JFile
						> iter = ilist.GetEnumerator(); iter.MoveNext(); )
					{
						hh.write("#include \"" + iter.Current.getName() + ".hh\"\n");
					}
					cc.write("#include \"" + fileName + ".hh\"\n");
					cc.write("#include \"utils.hh\"\n");
					for (System.Collections.Generic.IEnumerator<org.apache.hadoop.record.compiler.JRecord
						> iter_1 = rlist.GetEnumerator(); iter_1.MoveNext(); )
					{
						iter_1.Current.genCppCode(hh, cc, options);
					}
					hh.write("#endif //" + org.apache.hadoop.util.StringUtils.toUpperCase(fileName).Replace
						('.', '_') + "__\n");
				}
				finally
				{
					hh.close();
				}
			}
			finally
			{
				cc.close();
			}
		}
	}
}
